/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.modulorh.curriculo.view;

import br.com.ifba.modulorh.curriculo.model.Curriculo;
import br.com.ifba.modulorh.experienciaprofissional.model.ExperienciaProfissional;
import br.com.ifba.modulorh.experienciaprofissional.view.TelaCadastroExperienciaProfissional;
import br.com.ifba.modulorh.experienciaprofissional.view.TelaEditarExperienciaProfissional;
import br.com.ifba.modulorh.homescreen.TelaHomescreenGestor;
import br.com.ifba.modulorh.infrastructure.service.IFacade;
import java.awt.Font;
import java.io.File;
import java.awt.FontFormatException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 *
 * @author Kaio
 */
@Component
public class TelaEditarCurriculo extends javax.swing.JFrame {

    Font fonteMaior;
    Font fonteNormal;
    Font fonteMenor;
    
    private Curriculo curriculo;
    private List<ExperienciaProfissional> listaExperiencias;
    @Autowired
    private IFacade facade;
    @Autowired @Lazy
    private TelaDeListarCurriculo telaDeListarCurriculo;
    @Autowired @Lazy
    private TelaCadastroExperienciaProfissional telaCadastroExperienciaProfissional;
    @Autowired @Lazy
    private TelaEditarExperienciaProfissional telaEditarExperienciaProfissional;
    @Autowired @Lazy
    private TelaHomescreenGestor telaHomescreenGestor;
    private List<Long> idsRemover;
    
    ImageIcon icone = new ImageIcon("./src/main/resources/imagens/rh.png");
    
    public TelaEditarCurriculo() throws FontFormatException, IOException {
        this.fonteMaior = Font.createFont(Font.TRUETYPE_FONT,
                new File("./src/main/resources/fontes/Poppins/Poppins-Bold.ttf"))
                .deriveFont(Font.PLAIN, 28);
        this.fonteNormal = Font.createFont(Font.TRUETYPE_FONT,
                new File("./src/main/resources/fontes/Poppins/Poppins-Regular.ttf"))
                .deriveFont(Font.PLAIN, 16);
        this.fonteMenor = Font.createFont(Font.TRUETYPE_FONT,
                new File("./src/main/resources/fontes/Poppins/Poppins-SemiBold.ttf"))
                .deriveFont(Font.PLAIN, 14);
        initComponents();
        setLocationRelativeTo(null);
        this.listaExperiencias = new ArrayList<>();
        this.idsRemover = new ArrayList<>();
    }

    public void passandoDados(Curriculo curriculo){
        txtNome.setText(curriculo.getNome());
        txtEndereco.setText(curriculo.getEndereco());
        txtTelefone.setText(curriculo.getTelefone());
        txtEmail.setText(curriculo.getEmail());
        txtVaga.setText(curriculo.getVaga());
        txtFormacaoAcademica.setText(curriculo.getFormacaoAcademica());
        this.curriculo = curriculo;
        this.listaExperiencias = curriculo.getExperienciaProfissional();
        
        DefaultTableModel modelo = (DefaultTableModel) tblExperiencias.getModel();
        modelo.setNumRows(0);
        
        for (ExperienciaProfissional exp : this.listaExperiencias) {
            modelo.addRow(new Object[]{exp.getId(), exp.getCargo(),
                exp.getEmpresa(), exp.getPeriodo()});
        }
    }
    
    public void addExperiencia(ExperienciaProfissional expPro) {
        DefaultTableModel modelo = (DefaultTableModel) tblExperiencias.getModel();
        modelo.addRow(new Object[]{expPro.getId(), expPro.getCargo(),
            expPro.getEmpresa(), expPro.getPeriodo()});
        this.listaExperiencias.add(expPro);
    }
    
    public void editarExperiencia(ExperienciaProfissional expPro, int linhaEditar) {
        tblExperiencias.setValueAt(expPro.getId(), linhaEditar, 0);
        tblExperiencias.setValueAt(expPro.getCargo(), linhaEditar, 1);
        tblExperiencias.setValueAt(expPro.getEmpresa(), linhaEditar, 2);
        tblExperiencias.setValueAt(expPro.getPeriodo(), linhaEditar, 3);
        listaExperiencias.add(expPro);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlLateral = new javax.swing.JPanel();
        lblModuloRH = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        pnlEditarFuncionario = new javax.swing.JPanel();
        lblEditarFuncionario = new javax.swing.JLabel();
        pnlTextFields = new javax.swing.JPanel();
        txtFormacaoAcademica = new javax.swing.JTextField();
        txtVaga = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tblExperiencias = new javax.swing.JTable();
        btnInserirExperiencia = new javax.swing.JButton();
        btnEditarExperiencia = new javax.swing.JButton();
        btnRemoverExperiencia = new javax.swing.JButton();
        lblExperiencias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Currículo");
        setIconImage(icone.getImage());
        setResizable(false);

        pnlContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlContainer.setMaximumSize(new java.awt.Dimension(900, 600));
        pnlContainer.setMinimumSize(new java.awt.Dimension(900, 600));
        pnlContainer.setName(""); // NOI18N

        pnlLateral.setBackground(new java.awt.Color(26, 81, 107));
        pnlLateral.setMinimumSize(new java.awt.Dimension(293, 595));

        lblModuloRH.setFont(fonteMaior);
        lblModuloRH.setForeground(new java.awt.Color(255, 255, 255));
        lblModuloRH.setText("MÓDULO RH");

        btnInicio.setBackground(new java.awt.Color(26, 81, 107));
        btnInicio.setFont(fonteNormal);
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.setMaximumSize(new java.awt.Dimension(266, 40));
        btnInicio.setMinimumSize(new java.awt.Dimension(266, 40));
        btnInicio.setPreferredSize(new java.awt.Dimension(266, 40));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(26, 81, 107));
        btnVoltar.setFont(fonteNormal);
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVoltar.setFocusPainted(false);
        btnVoltar.setFocusable(false);
        btnVoltar.setMaximumSize(new java.awt.Dimension(266, 40));
        btnVoltar.setMinimumSize(new java.awt.Dimension(266, 40));
        btnVoltar.setPreferredSize(new java.awt.Dimension(266, 40));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLateralLayout = new javax.swing.GroupLayout(pnlLateral);
        pnlLateral.setLayout(pnlLateralLayout);
        pnlLateralLayout.setHorizontalGroup(
            pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLateralLayout.createSequentialGroup()
                .addGroup(pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLateralLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblModuloRH))
                    .addGroup(pnlLateralLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlLateralLayout.setVerticalGroup(
            pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLateralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblModuloRH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pnlEditarFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        pnlEditarFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 4, true));
        pnlEditarFuncionario.setMaximumSize(new java.awt.Dimension(388, 340));
        pnlEditarFuncionario.setPreferredSize(new java.awt.Dimension(388, 340));

        lblEditarFuncionario.setFont(fonteMaior);
        lblEditarFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditarFuncionario.setText("Editar Currículo");

        pnlTextFields.setBackground(new java.awt.Color(255, 255, 255));
        pnlTextFields.setMaximumSize(new java.awt.Dimension(360, 130));
        pnlTextFields.setPreferredSize(new java.awt.Dimension(360, 130));
        pnlTextFields.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFormacaoAcademica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFormacaoAcademica.setText("Formação Acadêmica");
        txtFormacaoAcademica.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtFormacaoAcademica.setMaximumSize(new java.awt.Dimension(320, 50));
        txtFormacaoAcademica.setMinimumSize(new java.awt.Dimension(320, 50));
        txtFormacaoAcademica.setPreferredSize(new java.awt.Dimension(320, 50));
        txtFormacaoAcademica.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFormacaoAcademicaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFormacaoAcademicaFocusLost(evt);
            }
        });
        pnlTextFields.add(txtFormacaoAcademica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 40));

        txtVaga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtVaga.setText("Vaga");
        txtVaga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtVaga.setMaximumSize(new java.awt.Dimension(320, 50));
        txtVaga.setMinimumSize(new java.awt.Dimension(320, 50));
        txtVaga.setPreferredSize(new java.awt.Dimension(320, 50));
        txtVaga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVagaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVagaFocusLost(evt);
            }
        });
        pnlTextFields.add(txtVaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 40));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmail.setText("Email");
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtEmail.setMaximumSize(new java.awt.Dimension(320, 50));
        txtEmail.setMinimumSize(new java.awt.Dimension(320, 50));
        txtEmail.setPreferredSize(new java.awt.Dimension(320, 50));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        pnlTextFields.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 40));

        txtTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTelefone.setText("Telefone");
        txtTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtTelefone.setMaximumSize(new java.awt.Dimension(320, 50));
        txtTelefone.setMinimumSize(new java.awt.Dimension(320, 50));
        txtTelefone.setPreferredSize(new java.awt.Dimension(320, 50));
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusLost(evt);
            }
        });
        pnlTextFields.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 40));

        txtEndereco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEndereco.setText("Endereço");
        txtEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtEndereco.setMaximumSize(new java.awt.Dimension(320, 50));
        txtEndereco.setMinimumSize(new java.awt.Dimension(320, 50));
        txtEndereco.setPreferredSize(new java.awt.Dimension(320, 50));
        txtEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEnderecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEnderecoFocusLost(evt);
            }
        });
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        pnlTextFields.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 40));

        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNome.setText("Nome");
        txtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtNome.setMaximumSize(new java.awt.Dimension(320, 50));
        txtNome.setMinimumSize(new java.awt.Dimension(320, 50));
        txtNome.setPreferredSize(new java.awt.Dimension(320, 50));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        pnlTextFields.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        btnEditar.setBackground(new java.awt.Color(71, 19, 35));
        btnEditar.setFont(fonteNormal);
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Salvar");
        btnEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditar.setFocusPainted(false);
        btnEditar.setFocusable(false);
        btnEditar.setMaximumSize(new java.awt.Dimension(266, 40));
        btnEditar.setMinimumSize(new java.awt.Dimension(266, 40));
        btnEditar.setPreferredSize(new java.awt.Dimension(266, 40));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlTextFields.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 40));

        jScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jScrollPane.setFont(fonteNormal);
        jScrollPane.setMinimumSize(new java.awt.Dimension(549, 427));
        jScrollPane.setPreferredSize(new java.awt.Dimension(559, 427));

        tblExperiencias.setFont(fonteMenor);
        tblExperiencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Cargo", "Empresa", "Período"
            }
        ));
        tblExperiencias.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tblExperiencias.setMinimumSize(new java.awt.Dimension(559, 427));
        tblExperiencias.setPreferredSize(new java.awt.Dimension(559, 427));
        jScrollPane.setViewportView(tblExperiencias);

        pnlTextFields.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 320, 120));

        btnInserirExperiencia.setFont(fonteMenor);
        btnInserirExperiencia.setText("INSERIR");
        btnInserirExperiencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnInserirExperiencia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInserirExperiencia.setFocusPainted(false);
        btnInserirExperiencia.setFocusable(false);
        btnInserirExperiencia.setMaximumSize(new java.awt.Dimension(266, 40));
        btnInserirExperiencia.setMinimumSize(new java.awt.Dimension(266, 40));
        btnInserirExperiencia.setPreferredSize(new java.awt.Dimension(266, 40));
        btnInserirExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirExperienciaActionPerformed(evt);
            }
        });
        pnlTextFields.add(btnInserirExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, 40));

        btnEditarExperiencia.setFont(fonteMenor);
        btnEditarExperiencia.setText("EDITAR");
        btnEditarExperiencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEditarExperiencia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarExperiencia.setFocusPainted(false);
        btnEditarExperiencia.setFocusable(false);
        btnEditarExperiencia.setMaximumSize(new java.awt.Dimension(266, 40));
        btnEditarExperiencia.setMinimumSize(new java.awt.Dimension(266, 40));
        btnEditarExperiencia.setPreferredSize(new java.awt.Dimension(266, 40));
        btnEditarExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarExperienciaActionPerformed(evt);
            }
        });
        pnlTextFields.add(btnEditarExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 100, 40));

        btnRemoverExperiencia.setFont(fonteMenor);
        btnRemoverExperiencia.setText("REMOVER");
        btnRemoverExperiencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnRemoverExperiencia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRemoverExperiencia.setFocusPainted(false);
        btnRemoverExperiencia.setFocusable(false);
        btnRemoverExperiencia.setMaximumSize(new java.awt.Dimension(266, 40));
        btnRemoverExperiencia.setMinimumSize(new java.awt.Dimension(266, 40));
        btnRemoverExperiencia.setPreferredSize(new java.awt.Dimension(266, 40));
        btnRemoverExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverExperienciaActionPerformed(evt);
            }
        });
        pnlTextFields.add(btnRemoverExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 100, 40));

        lblExperiencias.setFont(fonteMenor);
        lblExperiencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExperiencias.setText("Experiências Profissionais");
        pnlTextFields.add(lblExperiencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 320, -1));

        javax.swing.GroupLayout pnlEditarFuncionarioLayout = new javax.swing.GroupLayout(pnlEditarFuncionario);
        pnlEditarFuncionario.setLayout(pnlEditarFuncionarioLayout);
        pnlEditarFuncionarioLayout.setHorizontalGroup(
            pnlEditarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlEditarFuncionarioLayout.createSequentialGroup()
                        .addComponent(pnlTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEditarFuncionarioLayout.setVerticalGroup(
            pnlEditarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTextFields, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addComponent(pnlLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(pnlEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        this.setVisible(false);
        telaHomescreenGestor.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void txtFormacaoAcademicaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormacaoAcademicaFocusGained
        if(txtFormacaoAcademica.getText().equals("Formação Acadêmica"))
        txtFormacaoAcademica.setText("");
    }//GEN-LAST:event_txtFormacaoAcademicaFocusGained

    private void txtFormacaoAcademicaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormacaoAcademicaFocusLost
        if(txtFormacaoAcademica.getText().trim().isEmpty())
        txtFormacaoAcademica.setText("Formação Acadêmica");
    }//GEN-LAST:event_txtFormacaoAcademicaFocusLost

    private void txtVagaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVagaFocusGained
        if(txtVaga.getText().equals("Vaga"))
        txtVaga.setText("");
    }//GEN-LAST:event_txtVagaFocusGained

    private void txtVagaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVagaFocusLost
        if(txtVaga.getText().trim().isEmpty())
        txtVaga.setText("Vaga");
    }//GEN-LAST:event_txtVagaFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if(txtEmail.getText().equals("Email"))
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(txtEmail.getText().trim().isEmpty())
        txtEmail.setText("Email");
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusGained
        if(txtTelefone.getText().equals("Telefone"))
        txtTelefone.setText("");
    }//GEN-LAST:event_txtTelefoneFocusGained

    private void txtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusLost
        if(txtTelefone.getText().trim().isEmpty())
        txtTelefone.setText("Telefone");
    }//GEN-LAST:event_txtTelefoneFocusLost

    private void txtEnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoFocusGained
        if(txtEndereco.getText().equals("Endereço"))
        txtEndereco.setText("");
    }//GEN-LAST:event_txtEnderecoFocusGained

    private void txtEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoFocusLost
        if(txtEndereco.getText().trim().isEmpty())
        txtEndereco.setText("Endereço");
    }//GEN-LAST:event_txtEnderecoFocusLost

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        if(txtNome.getText().equals("Nome"))
        txtNome.setText("");
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if(txtNome.getText().trim().isEmpty())
        txtNome.setText("Nome");
    }//GEN-LAST:event_txtNomeFocusLost

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try{
            Curriculo curriculoEditado = new Curriculo(txtNome.getText(),
                    txtEndereco.getText(), txtTelefone.getText(),
                    txtEmail.getText(), txtVaga.getText(),
                    txtFormacaoAcademica.getText());

            curriculoEditado.setId(curriculo.getId());

            facade.updateCurriculo(curriculoEditado);
            
            for (ExperienciaProfissional exp: listaExperiencias) {
                exp.setCurriculo(curriculo);
                if (idsRemover.contains(exp.getId()) == false) {
                    facade.updateExperienciaProfissional(exp);
                }
            }
            
            telaDeListarCurriculo.atualizarTabela();
            telaDeListarCurriculo.setVisible(true);
            this.setVisible(false);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao Editar no banco: " + e.getMessage(),
                "Erro ao Editar no banco de dados!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void btnInserirExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirExperienciaActionPerformed
        this.setVisible(false);
        telaCadastroExperienciaProfissional.tipoTela(2);
        telaCadastroExperienciaProfissional.setVisible(true);
    }//GEN-LAST:event_btnInserirExperienciaActionPerformed

    private void btnEditarExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarExperienciaActionPerformed
        int linha = tblExperiencias.getSelectedRow();
        Long id = (Long) tblExperiencias.getValueAt(linha, 0);
        ExperienciaProfissional expPro = facade.findExperienciaProfissionalById(id);
        this.setVisible(false);
        telaEditarExperienciaProfissional.setVisible(true);
        telaEditarExperienciaProfissional.preencherDados(expPro, linha, 2);
        listaExperiencias.remove(expPro);
        
    }//GEN-LAST:event_btnEditarExperienciaActionPerformed

    private void btnRemoverExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverExperienciaActionPerformed
        int linha = tblExperiencias.getSelectedRow();
        Long id = (Long) tblExperiencias.getValueAt(linha, 0);
        DefaultTableModel modelo = (DefaultTableModel) tblExperiencias.getModel();
        ExperienciaProfissional expRemover = facade.findExperienciaProfissionalById(id);
        facade.deleteExperienciaProfissional(expRemover);
        modelo.removeRow(linha);
        this.idsRemover.add(id);
        listaExperiencias.remove(expRemover);
    }//GEN-LAST:event_btnRemoverExperienciaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.setVisible(false);
        telaDeListarCurriculo.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCurriculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCurriculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCurriculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarCurriculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaEditarCurriculo().setVisible(true);
                } catch (FontFormatException ex) {
                    Logger.getLogger(TelaEditarCurriculo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(TelaEditarCurriculo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarExperiencia;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInserirExperiencia;
    private javax.swing.JButton btnRemoverExperiencia;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblEditarFuncionario;
    private javax.swing.JLabel lblExperiencias;
    private javax.swing.JLabel lblModuloRH;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlEditarFuncionario;
    private javax.swing.JPanel pnlLateral;
    private javax.swing.JPanel pnlTextFields;
    private javax.swing.JTable tblExperiencias;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFormacaoAcademica;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtVaga;
    // End of variables declaration//GEN-END:variables
}
